before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/libs

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  LATEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - dockerize
  - deploy

build:
  image: openjdk:14
  stage: build
  script:
    - ./gradlew test
    - ./gradlew bootJar

dockerize:
  image: docker:19.03.8
  stage: dockerize
  services:
    - docker:19.03.8-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $LATEST_IMAGE_TAG || true
    - docker build --cache-from $LATEST_IMAGE_TAG -t $IMAGE_TAG -t $LATEST_IMAGE_TAG --build-arg PROFILE=prod --build-arg SCHEMA_REGISTRY_USERNAME=$SCHEMA_REGISTRY_USERNAME --build-arg SCHEMA_REGISTRY_PASSWORD=$SCHEMA_REGISTRY_PASSWORD .
    - docker push $IMAGE_TAG
    - docker push $LATEST_IMAGE_TAG
#  only:
#    - master

deploy:
  image: google/cloud-sdk:293.0.0
  stage: deploy
  script:
    - gcloud auth activate-service-account --key-file=$GKE_ACCESS_JSON
    - gcloud container clusters get-credentials lost-n-found-prod --zone europe-west3-a --project lost-n-found-311815
    - kubectl rollout restart deployment text-message-service
  only:
    - master