version: "3.8"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
#      - ~/docker/volumes/mongo:/data/user_db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js